package app.unifeed.social;
import app.unifeed.error.*; import app.unifeed.notification.NotificationService; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class SocialGraphService {private final JdbcTemplate jdbc;private final NotificationService notifications;public SocialGraphService(JdbcTemplate jdbc,NotificationService notifications){this.jdbc=jdbc;this.notifications=notifications;}
 @Transactional public boolean like(UUID post,UUID user){boolean created=jdbc.update("INSERT INTO post_likes(post_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",post,user)>0;if(created){UUID owner=jdbc.queryForObject("SELECT author_id FROM posts WHERE id=?",UUID.class,post);if(!owner.equals(user))notifications.create(owner,"LIKE",Map.of("postId",post,"actorId",user));}return created;}
 @Transactional public boolean unlike(UUID post,UUID user){return jdbc.update("DELETE FROM post_likes WHERE post_id=? AND user_id=?",post,user)>0;}
 @Transactional public UUID comment(UUID post,UUID user,UUID parent,String content){if(parent!=null){List<Integer> depths=jdbc.query("SELECT CASE WHEN parent_comment_id IS NULL THEN 1 ELSE 2 END FROM comments WHERE id=? AND post_id=?",(rs,n)->rs.getInt(1),parent,post);if(depths.isEmpty()||depths.getFirst()>1)throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);}UUID id=UUID.randomUUID();jdbc.update("INSERT INTO comments(id,post_id,user_id,parent_comment_id,content) VALUES(?,?,?,?,?)",id,post,user,parent,content);UUID owner=jdbc.queryForObject("SELECT author_id FROM posts WHERE id=?",UUID.class,post);if(!owner.equals(user))notifications.create(owner,"COMMENT",Map.of("postId",post,"commentId",id,"actorId",user));return id;}
 public List<CommentDto> comments(UUID post){return jdbc.query("SELECT c.id,c.user_id,u.display_name,u.avatar_path,c.parent_comment_id,c.content,c.created_at FROM comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? AND c.deleted_at IS NULL ORDER BY c.created_at",(rs,n)->new CommentDto((UUID)rs.getObject(1),(UUID)rs.getObject(2),rs.getString(3),rs.getString(4),(UUID)rs.getObject(5),rs.getString(6),rs.getTimestamp(7).toInstant()),post);}
 @Transactional public boolean follow(UUID from,UUID to){boolean created=jdbc.update("INSERT INTO follows(follower_id,following_id) VALUES(?,?) ON CONFLICT DO NOTHING",from,to)>0;if(created)notifications.create(to,"FOLLOW",Map.of("actorId",from));return created;}
 @Transactional public boolean unfollow(UUID from,UUID to){return jdbc.update("DELETE FROM follows WHERE follower_id=? AND following_id=?",from,to)>0;}
 public record CommentDto(UUID id,UUID userId,String displayName,String avatarPath,UUID parentId,String content,Instant createdAt){} }
