package app.unifeed.chat;
import app.unifeed.error.*; import app.unifeed.notification.NotificationService; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ChatService {private final JdbcTemplate jdbc;private final SimpMessagingTemplate ws;private final NotificationService notifications;public ChatService(JdbcTemplate jdbc,SimpMessagingTemplate ws,NotificationService notifications){this.jdbc=jdbc;this.ws=ws;this.notifications=notifications;}
 public List<ThreadDto> threads(UUID user){return jdbc.query("""
   SELECT t.id,t.type::text,t.club_id,
    COALESCE((SELECT string_agg(u.display_name, ', ') FROM thread_participants tp JOIN users u ON u.id=tp.user_id WHERE tp.thread_id=t.id AND tp.user_id<>?), 'Conversation'),
    (SELECT content FROM direct_messages dm WHERE dm.thread_id=t.id AND dm.deleted_at IS NULL ORDER BY dm.created_at DESC LIMIT 1),
    (SELECT created_at FROM direct_messages dm WHERE dm.thread_id=t.id AND dm.deleted_at IS NULL ORDER BY dm.created_at DESC LIMIT 1),
    (SELECT count(*) FROM direct_messages dm WHERE dm.thread_id=t.id AND dm.sender_id<>? AND dm.read_at IS NULL AND dm.deleted_at IS NULL)
   FROM conversation_threads t JOIN thread_participants mine ON mine.thread_id=t.id AND mine.user_id=?
   WHERE t.deleted_at IS NULL ORDER BY COALESCE((SELECT max(created_at) FROM direct_messages WHERE thread_id=t.id),t.created_at) DESC
   """,(rs,n)->new ThreadDto((UUID)rs.getObject(1),rs.getString(2),(UUID)rs.getObject(3),rs.getString(4),rs.getString(5),rs.getTimestamp(6)==null?null:rs.getTimestamp(6).toInstant(),rs.getLong(7)),user,user,user);}
 @Transactional public UUID directThread(UUID user,UUID participant){if(user.equals(participant))throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);List<UUID> existing=jdbc.query("""
   SELECT t.id FROM conversation_threads t JOIN thread_participants a ON a.thread_id=t.id AND a.user_id=? JOIN thread_participants b ON b.thread_id=t.id AND b.user_id=? WHERE t.type='DIRECT' AND t.deleted_at IS NULL AND (SELECT count(*) FROM thread_participants WHERE thread_id=t.id)=2 LIMIT 1
   """,(rs,n)->(UUID)rs.getObject(1),user,participant);if(!existing.isEmpty())return existing.getFirst();Integer found=jdbc.queryForObject("SELECT count(*) FROM users WHERE id=? AND deleted_at IS NULL",Integer.class,participant);if(found==null||found==0)throw new BusinessException(ErrorCode.COMMON_404_NOT_FOUND,HttpStatus.NOT_FOUND);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO conversation_threads(id,type) VALUES(?,'DIRECT')",id);jdbc.update("INSERT INTO thread_participants(thread_id,user_id) VALUES(?,?),(?,?)",id,user,id,participant);return id;}
 public List<MessageDto> history(UUID thread,UUID user,int limit){assertParticipant(thread,user);return jdbc.query("SELECT id,thread_id,sender_id,content,created_at,read_at FROM direct_messages WHERE thread_id=? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT ?",(rs,n)->new MessageDto((UUID)rs.getObject(1),(UUID)rs.getObject(2),(UUID)rs.getObject(3),rs.getString(4),rs.getTimestamp(5).toInstant(),rs.getTimestamp(6)==null?null:rs.getTimestamp(6).toInstant()),thread,Math.min(Math.max(limit,1),100));}
 @Transactional public MessageDto send(UUID thread,UUID sender,String content){assertParticipant(thread,sender);UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.update("INSERT INTO direct_messages(id,thread_id,sender_id,content) VALUES(?,?,?,?)",id,thread,sender,content);MessageDto dto=new MessageDto(id,thread,sender,content,now,null);ws.convertAndSend("/topic/chat/"+thread,dto);for(UUID recipient:jdbc.query("SELECT user_id FROM thread_participants WHERE thread_id=? AND user_id<>?",(rs,n)->(UUID)rs.getObject(1),thread,sender))notifications.create(recipient,"DIRECT_MESSAGE",Map.of("threadId",thread,"messageId",id,"senderId",sender,"content",content));return dto;}
 @Transactional public void markRead(UUID thread,UUID user){assertParticipant(thread,user);jdbc.update("UPDATE direct_messages SET read_at=COALESCE(read_at,now()) WHERE thread_id=? AND sender_id<>? AND deleted_at IS NULL",thread,user);}
 private void assertParticipant(UUID thread,UUID user){Integer member=jdbc.queryForObject("SELECT count(*) FROM thread_participants WHERE thread_id=? AND user_id=?",Integer.class,thread,user);if(member==null||member==0)throw new BusinessException(ErrorCode.COMMON_403_FORBIDDEN,HttpStatus.FORBIDDEN);}
 public record ThreadDto(UUID id,String type,UUID clubId,String title,String lastMessage,Instant lastMessageAt,long unreadCount){} public record MessageDto(UUID id,UUID threadId,UUID senderId,String content,Instant sentAt,Instant readAt){} }
