package app.unifeed.chat;
import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.Configuration; import org.springframework.messaging.*; import org.springframework.messaging.simp.config.*; import org.springframework.messaging.simp.stomp.*; import org.springframework.messaging.support.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.Authentication; import org.springframework.security.oauth2.jwt.JwtDecoder; import org.springframework.web.socket.config.annotation.*;
@Configuration @EnableWebSocketMessageBroker public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {private final JwtDecoder decoder;private final List<String> origins;private final Map<String,Authentication> sessions=new ConcurrentHashMap<>();public WebSocketConfig(JwtDecoder decoder,@Value("${app.frontend.allowed-origins:http://localhost:5173}")List<String>origins){this.decoder=decoder;this.origins=origins;}
 public void registerStompEndpoints(StompEndpointRegistry registry){registry.addEndpoint("/ws").setAllowedOrigins(origins.toArray(String[]::new)).withSockJS();}
 public void configureMessageBroker(MessageBrokerRegistry registry){registry.enableSimpleBroker("/topic","/queue");registry.setApplicationDestinationPrefixes("/app");registry.setUserDestinationPrefix("/user");}
 public void configureClientInboundChannel(ChannelRegistration registration){registration.interceptors(new ChannelInterceptor(){public Message<?> preSend(Message<?> message,MessageChannel channel){StompHeaderAccessor accessor=MessageHeaderAccessor.getAccessor(message,StompHeaderAccessor.class);if(accessor==null)return message;String session=accessor.getSessionId();if(StompCommand.CONNECT.equals(accessor.getCommand())||isRefresh(accessor)){Authentication auth=authenticate(accessor.getFirstNativeHeader("Authorization"));accessor.setUser(auth);if(session!=null)sessions.put(session,auth);return isRefresh(accessor)?null:message;}if(StompCommand.DISCONNECT.equals(accessor.getCommand())){if(session!=null)sessions.remove(session);return message;}Authentication auth=session==null?null:sessions.get(session);if(auth!=null)accessor.setUser(auth);return message;}});}
 private boolean isRefresh(StompHeaderAccessor accessor){return StompCommand.SEND.equals(accessor.getCommand())&&"/app/auth.refresh".equals(accessor.getDestination());}
 private Authentication authenticate(String header){if(header==null||!header.startsWith("Bearer "))throw new MessagingException("Missing bearer token");var jwt=decoder.decode(header.substring(7));return new UsernamePasswordAuthenticationToken(jwt.getSubject(),null,List.of());}
}
