package app.unifeed.club;
import app.unifeed.error.*; import app.unifeed.security.ClubPermissionEvaluator; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ClubEventService {
 private final JdbcTemplate jdbc; private final ClubPermissionEvaluator permissions; private final KafkaTemplate<String,Object> kafka; public ClubEventService(JdbcTemplate j,ClubPermissionEvaluator p,KafkaTemplate<String,Object> k){jdbc=j;permissions=p;kafka=k;}
 @Transactional public UUID createClub(UUID user,String name,String description){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO clubs(id,name,description,created_by) VALUES(?,?,?,?)",id,name,description,user);jdbc.update("INSERT INTO club_members(club_id,user_id,role) VALUES(?,?,'CLUB_ADMIN')",id,user);permissions.invalidate(id,user);return id;}
 @Transactional public UUID createEvent(UUID club,UUID user,String title,Instant starts){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO events(id,club_id,created_by,title,starts_at) VALUES(?,?,?,?,?)",id,club,user,title,java.sql.Timestamp.from(starts));return id;}
 @Transactional public void joinEvent(UUID user,UUID event){UUID club=jdbc.queryForObject("SELECT club_id FROM events WHERE id=? AND deleted_at IS NULL",UUID.class,event);jdbc.update("INSERT INTO club_members(club_id,user_id,role) VALUES(?,?,'CLUB_MEMBER') ON CONFLICT DO NOTHING",club,user);jdbc.update("INSERT INTO event_attendees(event_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",event,user);permissions.invalidate(club,user);kafka.send("email-events",event.toString(),Map.of("eventType","EVENT_REGISTRATION","userId",user.toString(),"eventId",event.toString()));}
 public List<Map<String,Object>> inviteCandidates(UUID club,UUID requester){return jdbc.queryForList("SELECT id,display_name FROM users u WHERE u.deleted_at IS NULL AND u.id<>? AND NOT EXISTS(SELECT 1 FROM club_members cm WHERE cm.club_id=? AND cm.user_id=u.id)",requester,club);}
 public Map<String,Object> detail(UUID club,UUID user){Map<String,Object> result=new LinkedHashMap<>(jdbc.queryForMap("SELECT id,name,description,cover_path,status::text FROM clubs WHERE id=? AND deleted_at IS NULL",club));List<String> roles=jdbc.query("SELECT role::text FROM club_members WHERE club_id=? AND user_id=?",(rs,n)->rs.getString(1),club,user);result.put("currentUserRole",roles.isEmpty()?null:roles.getFirst());return result;}
 public void transition(UUID club,String from,String to){if(!allowed(from,to))throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);jdbc.update("UPDATE clubs SET status=?::club_status WHERE id=? AND status=?::club_status",to,club,from);}
 private boolean allowed(String from,String to){return switch(from){case "PENDING_APPROVAL"->Set.of("ACTIVE","CLOSED").contains(to);case "ACTIVE"->Set.of("SUSPENDED","CLOSED").contains(to);case "SUSPENDED"->Set.of("ACTIVE","CLOSED").contains(to);default->false;};}
}
