package app.unifeed.club;
import app.unifeed.auth.AuthService; import app.unifeed.error.*; import app.unifeed.mail.EmailOutboxService; import app.unifeed.notification.NotificationService; import app.unifeed.security.ClubPermissionEvaluator; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ClubEventService {private final JdbcTemplate jdbc;private final ClubPermissionEvaluator permissions;private final EmailOutboxService emailOutbox;private final NotificationService notifications;public ClubEventService(JdbcTemplate jdbc,ClubPermissionEvaluator permissions,EmailOutboxService emailOutbox,NotificationService notifications){this.jdbc=jdbc;this.permissions=permissions;this.emailOutbox=emailOutbox;this.notifications=notifications;}
 @Transactional public UUID createClub(UUID user,ClubRequest r){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO clubs(id,name,description,category,logo_path,cover_path,created_by) VALUES(?,?,?,?,?,?,?)",id,r.name(),r.description(),r.category(),r.logoPath(),r.coverPath(),user);jdbc.update("INSERT INTO club_members(club_id,user_id,role) VALUES(?,?,'CLUB_ADMIN')",id,user);permissions.invalidate(id,user);return id;}
 @Transactional public UUID createEvent(UUID club,UUID user,EventRequest r){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO events(id,club_id,created_by,title,description,poster_path,starts_at,ends_at,location,category) VALUES(?,?,?,?,?,?,?,?,?,?)",id,club,user,r.title(),r.description(),r.posterPath(),java.sql.Timestamp.from(r.startsAt()),r.endsAt()==null?null:java.sql.Timestamp.from(r.endsAt()),r.location(),r.category());return id;}
 @Transactional public void joinClub(UUID user,UUID club){jdbc.update("INSERT INTO club_members(club_id,user_id,role) VALUES(?,?,'CLUB_MEMBER') ON CONFLICT DO NOTHING",club,user);permissions.invalidate(club,user);notifications.create(user,"CLUB_ENROLLMENT",Map.of("clubId",club));}
 @Transactional public void joinEvent(UUID user,UUID event){UUID club=jdbc.queryForObject("SELECT club_id FROM events WHERE id=? AND deleted_at IS NULL",UUID.class,event);joinClub(user,club);jdbc.update("INSERT INTO event_attendees(event_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",event,user);Map<String,Object> row=jdbc.queryForMap("SELECT email,display_name FROM users WHERE id=?",user);emailOutbox.enqueue("email-events",event.toString(),new AuthService.EmailEvent(UUID.randomUUID(),"EVENT_REGISTRATION",row.get("email").toString(),"en",Map.of("username",row.get("display_name").toString(),"eventDate",event.toString())));}
 @Transactional public UUID inviteClub(UUID club,UUID inviter,UUID invitee){requireClubAdmin(club,inviter);if(inviter.equals(invitee))throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);UUID existing=jdbc.query("SELECT id FROM invitations WHERE kind='CLUB' AND club_id=? AND invitee_id=? AND status='PENDING'",(rs,n)->(UUID)rs.getObject(1),club,invitee).stream().findFirst().orElse(null);if(existing!=null)return existing;UUID id=UUID.randomUUID();int created=jdbc.update("INSERT INTO invitations(id,kind,club_id,inviter_id,invitee_id) SELECT ?,'CLUB',?,?,? WHERE NOT EXISTS(SELECT 1 FROM club_members WHERE club_id=? AND user_id=?) ON CONFLICT DO NOTHING",id,club,inviter,invitee,club,invitee);if(created==0)throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);notifications.create(invitee,"CLUB_INVITATION",Map.of("invitationId",id,"clubId",club));return id;}
 @Transactional public UUID inviteEvent(UUID event,UUID inviter,UUID invitee){UUID club=jdbc.queryForObject("SELECT club_id FROM events WHERE id=?",UUID.class,event);requireClubAdmin(club,inviter);if(inviter.equals(invitee))throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);UUID existing=jdbc.query("SELECT id FROM invitations WHERE kind='EVENT' AND event_id=? AND invitee_id=? AND status='PENDING'",(rs,n)->(UUID)rs.getObject(1),event,invitee).stream().findFirst().orElse(null);if(existing!=null)return existing;UUID id=UUID.randomUUID();int created=jdbc.update("INSERT INTO invitations(id,kind,club_id,event_id,inviter_id,invitee_id) VALUES(?,'EVENT',?,?,?,?,?) ON CONFLICT DO NOTHING",id,club,event,inviter,invitee);if(created==0)throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);notifications.create(invitee,"EVENT_INVITATION",Map.of("invitationId",id,"clubId",club,"eventId",event));return id;}
 @Transactional public void respondInvitation(UUID id,UUID user,boolean accept){Map<String,Object> invitation=jdbc.queryForMap("SELECT kind,club_id,event_id FROM invitations WHERE id=? AND invitee_id=? AND status='PENDING' FOR UPDATE",id,user);if(jdbc.update("UPDATE invitations SET status=?::invitation_status,responded_at=now() WHERE id=?",accept?"ACCEPTED":"DECLINED",id)==0)throw new BusinessException(ErrorCode.COMMON_404_NOT_FOUND,HttpStatus.NOT_FOUND);if(accept){UUID club=(UUID)invitation.get("club_id");joinClub(user,club);if("EVENT".equals(invitation.get("kind")))jdbc.update("INSERT INTO event_attendees(event_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",invitation.get("event_id"),user);}}
 public List<InviteCandidateDto> inviteCandidates(UUID club,UUID requester){return jdbc.query("SELECT id,display_name,avatar_path FROM users u WHERE u.deleted_at IS NULL AND u.id<>? AND NOT EXISTS(SELECT 1 FROM club_members cm WHERE cm.club_id=? AND cm.user_id=u.id) AND NOT EXISTS(SELECT 1 FROM invitations i WHERE i.kind='CLUB' AND i.club_id=? AND i.invitee_id=u.id AND i.status='PENDING') ORDER BY display_name",(rs,n)->new InviteCandidateDto((UUID)rs.getObject(1),rs.getString(2),rs.getString(3)),requester,club,club);}
 public ClubDetailDto detail(UUID club,UUID user){List<ClubDetailDto> rows=jdbc.query("""
   SELECT c.id,c.name,c.description,c.category,c.logo_path,c.cover_path,c.status::text,
    (SELECT count(*) FROM club_members WHERE club_id=c.id),(SELECT count(*) FROM events WHERE club_id=c.id AND deleted_at IS NULL AND starts_at>now()),
    (SELECT role::text FROM club_members WHERE club_id=c.id AND user_id=? LIMIT 1)
   FROM clubs c WHERE c.id=? AND c.deleted_at IS NULL
   """,(rs,n)->new ClubDetailDto((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getLong(8),rs.getLong(9),rs.getString(10)),user,club);if(rows.isEmpty())throw new BusinessException(ErrorCode.COMMON_404_NOT_FOUND,HttpStatus.NOT_FOUND);return rows.getFirst();}
 public List<ClubSummaryDto> clubs(UUID user,String query,boolean mine,int limit){String search=query==null?"":query.trim();return jdbc.query("""
   SELECT c.id,c.name,c.description,c.category,c.logo_path,c.cover_path,c.status::text,count(cm.user_id),
    (SELECT role::text FROM club_members mine_role WHERE mine_role.club_id=c.id AND mine_role.user_id=? LIMIT 1)
   FROM clubs c LEFT JOIN club_members cm ON cm.club_id=c.id WHERE c.deleted_at IS NULL
    AND (?='' OR lower(c.name) LIKE lower('%'||?||'%'))
    AND (?=false OR EXISTS(SELECT 1 FROM club_members mine WHERE mine.club_id=c.id AND mine.user_id=?))
   GROUP BY c.id ORDER BY c.name LIMIT ?
   """,(rs,n)->new ClubSummaryDto((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getLong(8),rs.getString(9)),user,search,search,mine,user,Math.min(Math.max(limit,1),50));}
 public List<EventDto> events(UUID user,UUID club,String query,int limit){String search=query==null?"":query.trim();return jdbc.query("""
   SELECT e.id,e.club_id,c.name,e.title,e.description,e.poster_path,e.starts_at,e.ends_at,e.location,e.category,
    EXISTS(SELECT 1 FROM event_attendees a WHERE a.event_id=e.id AND a.user_id=?)
   FROM events e JOIN clubs c ON c.id=e.club_id WHERE e.deleted_at IS NULL AND c.deleted_at IS NULL AND e.starts_at>=now()
    AND (CAST(? AS UUID) IS NULL OR e.club_id=CAST(? AS UUID)) AND (?='' OR lower(e.title) LIKE lower('%'||?||'%')) ORDER BY e.starts_at LIMIT ?
   """,(rs,n)->event(rs,rs.getBoolean(11)),user,club,club,search,search,Math.min(Math.max(limit,1),50));}
 public EventDto event(UUID user,UUID id){List<EventDto> rows=jdbc.query("SELECT e.id,e.club_id,c.name,e.title,e.description,e.poster_path,e.starts_at,e.ends_at,e.location,e.category,EXISTS(SELECT 1 FROM event_attendees a WHERE a.event_id=e.id AND a.user_id=?) FROM events e JOIN clubs c ON c.id=e.club_id WHERE e.id=? AND e.deleted_at IS NULL",(rs,n)->event(rs,rs.getBoolean(11)),user,id);if(rows.isEmpty())throw new BusinessException(ErrorCode.COMMON_404_NOT_FOUND,HttpStatus.NOT_FOUND);return rows.getFirst();}
 public List<InviteCandidateDto> eventInviteCandidates(UUID event,UUID requester){return jdbc.query("SELECT u.id,u.display_name,u.avatar_path FROM users u WHERE u.deleted_at IS NULL AND u.id<>? AND NOT EXISTS(SELECT 1 FROM event_attendees ea WHERE ea.event_id=? AND ea.user_id=u.id) AND NOT EXISTS(SELECT 1 FROM invitations i WHERE i.kind='EVENT' AND i.event_id=? AND i.invitee_id=u.id AND i.status='PENDING') ORDER BY u.display_name",(rs,n)->new InviteCandidateDto((UUID)rs.getObject(1),rs.getString(2),rs.getString(3)),requester,event,event);}
 private void requireClubAdmin(UUID club,UUID user){if(!permissions.hasRole(club,new org.springframework.security.authentication.UsernamePasswordAuthenticationToken(user,null),"CLUB_ADMIN"))throw new BusinessException(ErrorCode.COMMON_403_FORBIDDEN,HttpStatus.FORBIDDEN);}
 private EventDto event(java.sql.ResultSet rs,boolean attending)throws java.sql.SQLException{return new EventDto((UUID)rs.getObject(1),(UUID)rs.getObject(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getTimestamp(7).toInstant(),rs.getTimestamp(8)==null?null:rs.getTimestamp(8).toInstant(),rs.getString(9),rs.getString(10),attending);}
 public void transition(UUID club,String from,String to){if(!allowed(from,to))throw new BusinessException(ErrorCode.COMMON_409_CONFLICT,HttpStatus.CONFLICT);jdbc.update("UPDATE clubs SET status=?::club_status WHERE id=? AND status=?::club_status",to,club,from);}
 private boolean allowed(String from,String to){return switch(from){case "PENDING_APPROVAL"->Set.of("ACTIVE","CLOSED").contains(to);case "ACTIVE"->Set.of("SUSPENDED","CLOSED").contains(to);case "SUSPENDED"->Set.of("ACTIVE","CLOSED").contains(to);default->false;};}
 public record ClubRequest(String name,String description,String category,String logoPath,String coverPath){} public record EventRequest(String title,String description,String posterPath,Instant startsAt,Instant endsAt,String location,String category){}
 public record ClubSummaryDto(UUID id,String name,String description,String category,String logoPath,String coverPath,String status,long memberCount,String currentUserRole){} public record ClubDetailDto(UUID id,String name,String description,String category,String logoPath,String coverPath,String status,long memberCount,long upcomingEventCount,String currentUserRole){} public record EventDto(UUID id,UUID clubId,String clubName,String title,String description,String posterPath,Instant startsAt,Instant endsAt,String location,String category,boolean attending){} public record InviteCandidateDto(UUID id,String displayName,String avatarPath){} }
