import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, GraduationCap, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Alert, Button, Input } from '@/components/ui';
import { useAuth, useForgotPassword, useLogin, useRegister, useResetPassword, useVerifyOtp } from '@/features/auth';
import { parseApiProblem } from '@/lib/api';
import i18n from '@/i18n';

function AuthLayout({children}:{children:ReactNode}){const {t}=useTranslation();return <main className="auth-layout"><section className="auth-brand" aria-label={t('common.appName')}><div className="auth-brand__glow"/><div className="relative z-10"><GraduationCap className="mb-6 size-14"/><div className="font-heading text-5xl font-extrabold">{t('common.appName')}</div><p className="mt-3 text-2xl font-semibold text-white/75">{t('brand.tagline')}</p></div><p className="relative z-10 text-white/70">{t('brand.description')}</p></section><section className="auth-panel"><div className="w-full max-w-xl">{children}</div></section></main>}
const message=(error:unknown)=>{if(!error)return null;const problem=parseApiProblem(error);return problem.code?i18n.t(`errors.${problem.code}`,{defaultValue:problem.detail}):problem.detail;};
const testVersionWarning='⚠️ Test Sürümü Uyarısı: Şu an test aşamasında olduğumuz için Gmail adresinizle giriş yapabiliyorsunuz. Canlı sürümde yalnızca üniversite e-posta adresiniz (.edu / .edu.tr) geçerli olacaktır.';

export function LoginPage(){const {t}=useTranslation();const nav=useNavigate();const auth=useAuth();const login=useLogin();const [show,setShow]=useState(false);if(auth.isAuthenticated)return <Navigate to="/" replace/>;const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);login.mutate({email:String(form.get('email')),password:String(form.get('password'))},{onSuccess:()=>nav('/')});};return <AuthLayout><div className="mb-8"><p className="eyebrow">{t('auth.campusAccess')}</p><h1 className="page-title mt-2">{t('auth.welcomeBack')}</h1><p className="text-muted-foreground">{t('auth.signInHint')}</p></div><Alert variant="warning" className="mb-6">{testVersionWarning}</Alert>{login.error&&<Alert variant="danger" className="mb-4">{message(login.error)}</Alert>}<form className="grid gap-5" onSubmit={submit}><Input name="email" type="email" label={t('auth.email')} placeholder="student@university.edu" leadingIcon={<Mail className="size-5"/>} required/><Input name="password" type={show?'text':'password'} label={t('auth.password')} leadingIcon={<LockKeyhole className="size-5"/>} trailingIcon={<button type="button" aria-label={t('auth.togglePassword')} onClick={()=>setShow(v=>!v)}>{show?<EyeOff className="size-5"/>:<Eye className="size-5"/>}</button>} required/><div className="flex justify-end"><Link className="link" to="/auth/forgot-password">{t('auth.forgot')}</Link></div><Button type="submit" size="lg" loading={login.isPending} className="w-full">{t('auth.signIn')}</Button></form><p className="mt-8 text-center text-sm text-muted-foreground">{t('auth.noAccount')} <Link className="link" to="/auth/register">{t('auth.signUp')}</Link></p></AuthLayout>}

export function RegisterPage(){const {t}=useTranslation();const nav=useNavigate();const register=useRegister();const [show,setShow]=useState(false);const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const email=String(form.get('email'));register.mutate({displayName:String(form.get('displayName')),email,password:String(form.get('password'))},{onSuccess:()=>nav('/auth/verify',{state:{email}})});};return <AuthLayout><p className="eyebrow">{t('auth.joinCampus')}</p><h1 className="page-title mt-2">{t('auth.createAccount')}</h1><p className="mb-6 text-muted-foreground">{t('auth.createHint')}</p><Alert variant="warning" className="mb-6">{testVersionWarning}</Alert>{register.error&&<Alert variant="danger" className="mb-4">{message(register.error)}</Alert>}<form className="grid gap-5" onSubmit={submit}><Input name="displayName" label={t('auth.fullName')} leadingIcon={<UserRound className="size-5"/>} required/><Input name="email" type="email" label={t('auth.email')} leadingIcon={<Mail className="size-5"/>} hint=".edu / .edu.tr" required/><Input name="password" type={show?'text':'password'} minLength={8} label={t('auth.password')} leadingIcon={<LockKeyhole className="size-5"/>} trailingIcon={<button type="button" onClick={()=>setShow(v=>!v)} aria-label={t('auth.togglePassword')}>{show?<EyeOff className="size-5"/>:<Eye className="size-5"/>}</button>} required/><Button type="submit" size="lg" loading={register.isPending}>{t('auth.createAccount')}</Button></form><p className="mt-7 text-center text-sm text-muted-foreground">{t('auth.haveAccount')} <Link className="link" to="/auth/login">{t('auth.signIn')}</Link></p></AuthLayout>}

export function VerifyOtpPage(){const {t}=useTranslation();const nav=useNavigate();const location=useLocation();const verify=useVerifyOtp();const [email,setEmail]=useState(String((location.state as {email?:string}|null)?.email??''));const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const otp=String(new FormData(e.currentTarget).get('otp'));verify.mutate({email,otp},{onSuccess:()=>nav('/')});};return <AuthLayout><h1 className="page-title">{t('auth.verifyTitle')}</h1><p className="mb-6 text-muted-foreground">{t('auth.verifyHint')}</p>{verify.error&&<Alert variant="danger" className="mb-4">{message(verify.error)}</Alert>}<form className="grid gap-5" onSubmit={submit}><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} label={t('auth.email')} required/><Input name="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} label={t('auth.otp')} className="text-center text-2xl tracking-[0.5em]" required/><Button type="submit" loading={verify.isPending}>{t('auth.verify')}</Button></form></AuthLayout>}

export function ForgotPasswordPage(){const {t}=useTranslation();const forgot=useForgotPassword();const [sent,setSent]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();forgot.mutate(String(new FormData(e.currentTarget).get('email')),{onSuccess:()=>setSent(true)});};return <AuthLayout><h1 className="page-title">{t('auth.resetTitle')}</h1><p className="mb-6 text-muted-foreground">{t('auth.resetHint')}</p>{sent?<><Alert variant="success">{t('auth.resetSent')}</Alert><Link className="mt-5 block text-center link" to="/auth/reset-password">{t('auth.enterResetCode')}</Link></>:<form className="grid gap-5" onSubmit={submit}><Input name="email" type="email" label={t('auth.email')} required/><Button type="submit" loading={forgot.isPending}>{t('auth.sendCode')}</Button></form>}</AuthLayout>}

export function ResetPasswordPage(){const {t}=useTranslation();const nav=useNavigate();const reset=useResetPassword();const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);reset.mutate({email:String(f.get('email')),token:String(f.get('token')),newPassword:String(f.get('newPassword'))},{onSuccess:()=>nav('/auth/login')});};return <AuthLayout><h1 className="page-title">{t('auth.newPassword')}</h1>{reset.error&&<Alert variant="danger" className="my-4">{message(reset.error)}</Alert>}<form className="mt-6 grid gap-5" onSubmit={submit}><Input name="email" type="email" label={t('auth.email')} required/><Input name="token" maxLength={6} label={t('auth.otp')} required/><Input name="newPassword" type="password" minLength={8} label={t('auth.newPassword')} required/><Button type="submit" loading={reset.isPending}>{t('auth.savePassword')}</Button></form></AuthLayout>}
