export const tr = {
  translation: {
    common: {
      appName: 'UniFeed', loading: 'Yükleniyor…', save: 'Kaydet', saving: 'Kaydediliyor…', cancel: 'İptal', discard: 'Vazgeç', close: 'Kapat', delete: 'Sil', edit: 'Düzenle', create: 'Oluştur', publish: 'Yayınla', share: 'Paylaş', send: 'Gönder', search: 'Ara', retry: 'Tekrar dene', back: 'Geri', next: 'İleri', previous: 'Önceki', confirm: 'Onayla', yes: 'Evet', no: 'Hayır', more: 'Daha fazla', seeAll: 'Tümünü gör', noResults: 'Sonuç bulunamadı', optional: 'İsteğe bağlı', required: 'Zorunlu', success: 'İşlem tamamlandı', unknownError: 'Beklenmeyen bir hata oluştu.', language: 'Dil', turkish: 'Türkçe', english: 'English', or: 'veya', testVersion: 'Test sürümü', student: 'Öğrenci', club: 'Kulüp', community: 'Topluluk', locationTba: 'Konum açıklanacak',
    },
    nav: { home: 'Ana Sayfa', discover: 'Keşfet', community: 'Kulüp ve Etkinlikler', clubs: 'Kulüpler', events: 'Etkinlikler', messages: 'Mesajlar', notifications: 'Bildirimler', profile: 'Profil', settings: 'Ayarlar', logout: 'Çıkış yap' },
    brand: { tagline: 'Campus life, connected.', description: 'Kampüs topluluğuna katıl, kulüpleri keşfet ve birlikte üret.', hub: 'Campus Hub' },
    a11y: { mainNavigation: 'Ana navigasyon', mainMenu: 'Ana menü', mobileNavigation: 'Mobil navigasyon', homeLink: 'UniFeed ana sayfa', openMenu: 'Menüyü aç', createPost: 'Gönderi oluştur', logout: 'Çıkış yap', notificationsCount: '{{count}} yeni bildirim', closeNotification: 'Bildirimi kapat', postImage: 'Gönderi görseli', eventPoster: 'Etkinlik afişi', storyBy: '{{name}} hikâyesi', statusOnline: 'Çevrimiçi', statusOffline: 'Çevrimdışı', statusBusy: 'Meşgul' },
    auth: {
      welcome: 'UniFeed’e hoş geldin', subtitle: 'Kampüsündeki herkese ve her şeye bağlan.', login: 'Giriş Yap', register: 'Kayıt Ol', email: 'E-posta', password: 'Şifre', displayName: 'Ad Soyad', fullName: 'Ad soyad', forgotPassword: 'Şifremi unuttum', forgot: 'Şifremi unuttum', rememberMe: 'Beni hatırla', noAccount: 'Hesabın yok mu?', hasAccount: 'Zaten hesabın var mı?', haveAccount: 'Zaten hesabın var mı?', continueWithGoogle: 'Google ile devam et', continueGoogle: 'Google ile devam et', academicEmailHint: 'Üniversite e-posta adresini kullan.', verifyTitle: 'E-postanı doğrula', verifyDescription: 'E-posta adresine gönderilen 6 haneli kodu gir.', verifyHint: 'E-posta adresine gönderilen 6 haneli kodu gir.', verificationCode: 'Doğrulama kodu', otp: 'Doğrulama kodu', verify: 'Doğrula', resendCode: 'Kodu tekrar gönder', resetTitle: 'Şifreni sıfırla', resetDescription: 'Sıfırlama kodunu ve yeni şifreni gir.', resetHint: 'Sıfırlama bağlantısı için e-posta adresini gir.', resetSent: 'Sıfırlama kodu e-posta adresine gönderildi.', enterResetCode: 'Sıfırlama kodunu gir', newPassword: 'Yeni şifre', sendResetCode: 'Sıfırlama kodu gönder', sendCode: 'Kod gönder', savePassword: 'Şifreyi kaydet', logoutConfirm: 'Çıkış yapmak istediğine emin misin?', sessionExpired: 'Oturumun sona erdi. Lütfen tekrar giriş yap.', campusAccess: 'KAMPÜS ERİŞİMİ', welcomeBack: 'Tekrar hoş geldin', signInHint: 'Kampüsündeki gelişmeleri kaçırma.', testWarning: 'Bu ortam yalnızca test amaçlıdır.', togglePassword: 'Şifre görünürlüğünü değiştir', signIn: 'Giriş yap', signUp: 'Kayıt ol', joinCampus: 'KAMPÜSE KATIL', createAccount: 'Hesap oluştur', createHint: 'Kampüs topluluğuna katılmak için bilgilerini gir.', domainHint: 'Yalnızca .edu veya .edu.tr uzantılı e-posta adresleri kabul edilir.', finishing: 'Giriş tamamlanıyor', pleaseWait: 'Lütfen bekle…', backLogin: 'Giriş sayfasına dön',
    },
    feed: { title: 'Ana Sayfa', eyebrow: 'KAMPÜS AKIŞI', heading: 'Bugün neler oluyor?', createPost: 'Gönderi oluştur', createDescription: 'Kampüs topluluğunla bir şeyler paylaş.', composerLabel: 'Ne düşünüyorsun?', image: 'Görsel', post: 'Paylaş', like: 'Beğen', unlike: 'Beğenmekten vazgeç', comment: 'Yorum yap', comments: 'Yorumlar', commentLabel: 'Yorum', commentPlaceholder: 'Yorum yaz...', firstComment: 'İlk yorumu sen yap.', noPosts: 'Akışın henüz sakin', noPostsDescription: 'Kulüplere katıldıkça ve öğrencileri takip ettikçe içerikler burada görünür.', loadMore: 'Daha fazla yükle', deleteConfirm: 'Bu gönderiyi silmek istediğine emin misin?', notFound: 'Gönderi bulunamadı', story: 'Hikâye', stories: 'Hikâyeler', addStory: 'Hikâye ekle', storyPublished: 'Hikâyen yayınlandı.', storyPublishError: 'Hikâye yayınlanamadı.', storyViewError: 'Hikâye görüntüleme bilgisi kaydedilemedi.', commentError: 'Yorum gönderilemedi.', likeError: 'Beğeni güncellenemedi.', linkCopied: 'Bağlantı kopyalandı.', shareError: 'Paylaşım başlatılamadı.', published: 'Gönderi yayınlandı.', publishError: 'Gönderi yayınlanamadı.' },
    profile: { avatar: 'Profil fotoğrafı', followers: 'takipçi', following: 'takip', clubs: 'kulüp', follow: 'Takip et', unfollow: 'Takibi bırak', sendMessage: 'Mesaj Gönder', followersTitle: 'Takipçiler', followingTitle: 'Takip Edilenler', clubsTitle: 'Üye Olunan Kulüpler', listEmpty: 'Gösterilecek kayıt yok.', editProfile: 'Profili düzenle', bio: 'Biyografi', department: 'Bölüm', academicYear: 'Sınıf', posts: 'Gönderiler', noPosts: 'Henüz gönderi yok', notFound: 'Profil bulunamadı', testAccount: 'Test hesabı', departmentMissing: 'Bölüm belirtilmedi', bioMissing: 'Henüz bir biyografi yok.', likesCount: '{{count}} beğeni', commentsCount: '{{count}} yorum' },
    clubs: { title: 'Kulüpler', myClubs: 'Kulüplerim', discover: 'Kulüpleri keşfet', members: '{{count}} üye', memberLabel: 'üye', join: 'Kulübe katıl', joined: 'Üyesin', createClub: 'Kulüp oluştur', name: 'Kulüp adı', description: 'Açıklama', category: 'Kategori', upcomingEvents: 'Yaklaşan etkinlikler', upcomingCount: '{{count}} yaklaşan etkinlik', invite: 'Davet Et', invited: 'Davet edildi', noClubs: 'Kulüp bulunamadı', searchPlaceholder: 'Kulüp veya etkinlik ara', eyebrow: 'TOPLULUK', heading: 'Kulüpler ve etkinlikler', defaultDescription: 'Kampüs topluluğu', missingDescription: 'Bu kulüp henüz açıklama eklemedi.', createTitle: 'Yeni bir topluluk oluştur', createSubtitle: 'Kulübünün kimliğini kampüse tanıt.', categoryPlaceholder: 'Kategori seç', logo: 'Kulüp logosu', cover: 'Kapak görseli', created: 'Kulüp oluşturuldu.', createError: 'Kulüp oluşturulamadı.', categories: { academic: 'Akademik', cultureArts: 'Kültür ve Sanat', sport: 'Spor', technology: 'Teknoloji', socialResponsibility: 'Sosyal Sorumluluk' } },
    events: { title: 'Etkinlikler', upcoming: 'Yaklaşan etkinlikler', join: 'Etkinliğe katıl', attending: 'Katılıyorsun', createEvent: 'Etkinlik oluştur', eventTitle: 'Etkinlik adı', date: 'Tarih', startTime: 'Başlangıç', endTime: 'Bitiş', location: 'Konum', noEvents: 'Etkinlik bulunamadı', missingDescription: 'Etkinlik açıklaması yakında paylaşılacak.', createSubtitle: 'Tüm ayrıntıları tek yerde planla.', organizerClub: 'Organizatör kulüp', clubPlaceholder: 'Kulüp seç', category: 'Kategori', poster: 'Etkinlik afişi', description: 'Açıklama', publish: 'Etkinliği yayınla', created: 'Etkinlik oluşturuldu.', createError: 'Etkinlik oluşturulamadı. Kulüp yöneticisi yetkisi gerekir.' },
    chat: { title: 'Mesajlar', newMessage: 'Yeni mesaj', newChat: 'Yeni sohbet', chat: 'Sohbet', message: 'Mesaj', messagePlaceholder: 'Bir mesaj yaz...', noMessages: 'Henüz mesaj yok', selectConversation: 'Bir sohbet seç', selectDescription: 'Mesajlaşmaya kaldığın yerden devam et.', details: 'Sohbet ayrıntıları', privacy: 'Mesajlar gerçek zamanlı ve yalnızca sohbet katılımcılarına iletilir.', studentSearch: 'Öğrenci ara', online: 'Çevrimiçi', typing: 'yazıyor…', connectionError: 'Mesaj bağlantısı kuruluyor, lütfen tekrar dene.' },
    notifications: { title: 'Bildirimler', eyebrow: 'GÜNCELLEMELER', all: 'Tümü', unread: 'Okunmamış', markAllRead: 'Tümünü okundu işaretle', empty: 'Yeni bildirimin yok', emptyDescription: 'Kulüp ve arkadaş güncellemeleri burada görünür.', fallback: 'Yeni bildirimin var', like: 'Gönderin beğenildi', comment: 'Gönderine yorum yapıldı', follow: 'Yeni bir takipçin var', event: 'Etkinlik hatırlatması', club: 'Kulüp güncellemesi' },
    invitations: { pickerTitle: 'Öğrenci davet et', noCandidates: 'Davet edilebilecek kişi kalmadı.', sent: 'Davet gönderildi.', sendError: 'Davet gönderilemedi.', clubReceived: 'Bir kulübe davet edildin.', eventReceived: 'Bir etkinliğe davet edildin.', accept: 'Kabul et', decline: 'Reddet', accepted: 'Davet kabul edildi.', declined: 'Davet reddedildi.', responseError: 'Davete yanıt verilemedi.' },
    search: { title: 'Ara', eyebrow: 'KEŞFET', heading: 'Kampüsü keşfet', placeholder: 'Kişi, kulüp veya etkinlik ara', users: 'Öğrenciler', clubs: 'Kulüpler', events: 'Etkinlikler', empty: 'Aramana uygun sonuç bulunamadı.', start: 'Aramaya başla', minCharacters: 'En az iki karakter yaz.' },
    settings: { title: 'Ayarlar', eyebrow: 'TERCİHLER', account: 'Hesap', appearance: 'Görünüm', appearanceHint: 'Açık veya koyu tema', lightTheme: 'Açık tema', darkTheme: 'Koyu tema', language: 'Dil', languageHint: 'Arayüz dili', privacy: 'Gizlilik', notifications: 'Bildirimler' },
    editor: { eyebrow: 'OLUŞTUR' },
    notFound: { title: 'Bu sayfa bulunamadı', description: 'Bağlantı değişmiş veya içerik kaldırılmış olabilir.', home: 'Ana sayfaya dön' },
    toast: { mutationTitle: 'İşlem tamamlanamadı.', mutationDescription: 'Lütfen bağlantını kontrol edip tekrar dene.' },
    errorBoundary: { title: 'Bir şeyler ters gitti', description: 'Sayfa güvenli biçimde durduruldu. Yenileyerek tekrar deneyebilirsin.', reload: 'Sayfayı yenile' },
    errors: { AUTH_001_DOMAIN_REJECTED: 'Yalnızca akademik e-posta adresleri kabul edilir.', AUTH_009_INVALID_REFRESH_TOKEN: 'Oturumun geçersiz veya süresi dolmuş.', AUTH_010_INVALID_OTP: 'Doğrulama kodu geçersiz veya süresi dolmuş.', AUTH_011_INVALID_CREDENTIALS: 'E-posta veya şifre hatalı.', AUTH_012_EMAIL_NOT_VERIFIED: 'Devam etmek için e-posta adresini doğrula.', AUTH_013_INVALID_RESET_TOKEN: 'Şifre sıfırlama kodu geçersiz veya süresi dolmuş.', AUTH_014_EMAIL_ALREADY_REGISTERED: 'Bu e-posta adresiyle zaten bir hesap bulunuyor.', COMMON_001_VALIDATION_FAILED: 'Lütfen işaretli alanları kontrol et.', COMMON_403_FORBIDDEN: 'Bu işlem için yetkin yok.', COMMON_404_NOT_FOUND: 'Aradığın içerik bulunamadı.', COMMON_409_CONFLICT: 'İşlem mevcut durumla çakışıyor.', COMMON_500_INTERNAL_ERROR: 'Sunucuda bir hata oluştu. Lütfen tekrar dene.' },
  },
} as const;
