import { useState, type FormEvent, type ReactNode } from 'react';
import { CalendarDays, MapPin, Plus, Search, Users } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Avatar, Badge, Button, Card, CardContent, EmptyState, Input, Select, Skeleton, Textarea, useToast } from '@/components/ui';
import { InvitationPicker, mediaUrl, useActions, useClub, useClubs, useCreateClub, useCreateEvent, useEvent, useEvents } from '@/features/data';
import { formatDateTime } from '@/lib/date';

const formatEventDate=(value:string,locale:string)=>formatDateTime(value,locale,{dateStyle:'long',timeStyle:'short'});
const categoryKeys=['academic','cultureArts','sport','technology','socialResponsibility'] as const;

export function CommunityPage(){const{t,i18n}=useTranslation();const[search,setSearch]=useState('');const clubs=useClubs(false,search);const events=useEvents(undefined,search);const canCreateEvent=clubs.data?.some(club=>club.currentUserRole==='CLUB_ADMIN');return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">{t('clubs.eyebrow')}</p><h1 className="font-heading text-3xl font-extrabold">{t('clubs.heading')}</h1></div><div className="flex gap-2"><Link to="/clubs/new" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-primary px-5 font-semibold text-primary"><Plus className="size-4"/>{t('clubs.createClub')}</Link>{canCreateEvent&&<Link to="/events/new" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-5 font-semibold text-white"><Plus className="size-4"/>{t('events.createEvent')}</Link>}</div></div><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('clubs.searchPlaceholder')} leadingIcon={<Search className="size-5"/>} containerClassName="my-6 max-w-xl"/>
<section><h2 className="mb-4 font-heading text-2xl font-bold">{t('clubs.title')}</h2>{clubs.isLoading?<Skeleton className="h-48"/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{clubs.data?.map(club=><Link key={club.id} to={`/clubs/${club.id}`}><Card className="h-full overflow-hidden transition hover:-translate-y-1 hover:shadow-lg">{club.coverPath&&<img src={mediaUrl(club.coverPath)} alt="" className="h-28 w-full object-cover"/>}<CardContent><div className="flex items-center gap-3"><Avatar src={mediaUrl(club.logoPath)} name={club.name} alt={club.name}/><div><h3 className="font-heading text-lg font-bold">{club.name}</h3><Badge variant="success">{club.category||t('common.community')}</Badge></div></div><p className="mt-4 line-clamp-2 text-sm text-muted-foreground">{club.description||t('clubs.defaultDescription')}</p><p className="mt-4 flex items-center gap-2 text-sm"><Users className="size-4"/>{t('clubs.members',{count:club.memberCount})}</p></CardContent></Card></Link>)}</div>}</section>
<section className="mt-10"><h2 className="mb-4 font-heading text-2xl font-bold">{t('events.upcoming')}</h2>{events.isLoading?<Skeleton className="h-48"/>:<div className="grid gap-4 md:grid-cols-2">{events.data?.map(event=><Link key={event.id} to={`/events/${event.id}`}><Card className="h-full overflow-hidden transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="flex gap-4">{event.posterPath?<img src={mediaUrl(event.posterPath)} alt="" className="h-28 w-24 rounded-lg object-cover"/>:<div className="grid h-28 w-24 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><CalendarDays/></div>}<div><Badge>{event.clubName}</Badge><h3 className="mt-2 font-heading text-lg font-bold">{event.title}</h3><p className="mt-2 text-sm text-muted-foreground">{formatEventDate(event.startsAt,i18n.language)}</p><p className="mt-1 flex items-center gap-1 text-sm"><MapPin className="size-4"/>{event.location||t('common.locationTba')}</p></div></CardContent></Card></Link>)}</div>}</section></div>}

export function ClubDetailPage(){const{t,i18n}=useTranslation();const{id}=useParams();const club=useClub(id);const events=useEvents(id);const actions=useActions();if(club.isLoading)return <Skeleton className="h-96"/>;if(!club.data)return <EmptyState title={t('clubs.noClubs')}/>;const c=club.data;const admin=c.currentUserRole==='CLUB_ADMIN';return <div><Card className="overflow-hidden">{c.coverPath?<img src={mediaUrl(c.coverPath)} alt="" className="h-52 w-full object-cover"/>:<div className="h-40 bg-gradient-to-r from-primary to-secondary"/>}<CardContent className="relative"><Avatar src={mediaUrl(c.logoPath)} name={c.name} alt={c.name} className="-mt-16 size-24 border-4 border-card"/><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><Badge variant="success">{c.category||t('common.club')}</Badge><h1 className="mt-2 font-heading text-3xl font-extrabold">{c.name}</h1><p className="mt-3 max-w-3xl text-muted-foreground">{c.description||t('clubs.missingDescription')}</p></div><div className="flex flex-wrap gap-2">{admin&&<InvitationPicker resource="clubs" resourceId={c.id}/>}<Button disabled={Boolean(c.currentUserRole)||actions.joinClub.isPending} onClick={()=>actions.joinClub.mutate(c.id)}>{c.currentUserRole?t('clubs.joined'):t('clubs.join')}</Button></div></div><div className="mt-6 flex gap-6 text-sm"><span>{t('clubs.members',{count:c.memberCount})}</span><span>{t('clubs.upcomingCount',{count:c.upcomingEventCount||0})}</span></div></CardContent></Card><h2 className="mb-4 mt-8 font-heading text-2xl font-bold">{t('events.title')}</h2><div className="grid gap-4 md:grid-cols-2">{events.data?.map(e=><Link key={e.id} to={`/events/${e.id}`}><Card><CardContent><Badge>{formatEventDate(e.startsAt,i18n.language)}</Badge><h3 className="mt-3 font-heading text-xl font-bold">{e.title}</h3><p className="mt-2 text-sm text-muted-foreground">{e.location}</p></CardContent></Card></Link>)}</div></div>}

export function EventDetailPage(){const{t,i18n}=useTranslation();const{id}=useParams();const event=useEvent(id);const actions=useActions();const ownerClub=useClub(event.data?.clubId);if(event.isLoading)return <Skeleton className="h-96"/>;if(!event.data)return <EmptyState title={t('events.noEvents')}/>;const e=event.data;const admin=ownerClub.data?.currentUserRole==='CLUB_ADMIN';return <Card className="mx-auto max-w-4xl overflow-hidden">{e.posterPath&&<img src={mediaUrl(e.posterPath)} alt={t('a11y.eventPoster')} className="max-h-[420px] w-full object-cover"/>}<CardContent><Badge>{e.clubName}</Badge><h1 className="mt-3 font-heading text-3xl font-extrabold sm:text-4xl">{e.title}</h1><div className="mt-5 grid gap-3 rounded-xl bg-surface-low p-4 sm:grid-cols-2"><p className="flex gap-2"><CalendarDays className="size-5 text-primary"/>{formatEventDate(e.startsAt,i18n.language)}</p><p className="flex gap-2"><MapPin className="size-5 text-primary"/>{e.location||t('common.locationTba')}</p></div><p className="mt-6 whitespace-pre-wrap leading-7 text-muted-foreground">{e.description||t('events.missingDescription')}</p><div className="mt-7 flex flex-wrap gap-2">{admin&&<InvitationPicker resource="events" resourceId={e.id}/>}<Button disabled={e.attending||actions.joinEvent.isPending} onClick={()=>actions.joinEvent.mutate(e.id)}>{e.attending?t('events.attending'):t('events.join')}</Button></div></CardContent></Card>}

export function ClubCreatePage(){const{t}=useTranslation();const nav=useNavigate();const toast=useToast();const mutation=useCreateClub();const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();mutation.mutate(new FormData(e.currentTarget),{onSuccess:r=>{toast.success(t('clubs.created'));nav(`/clubs/${r.id}`)},onError:()=>toast.error(t('clubs.createError'))})};return <Editor title={t('clubs.createTitle')} subtitle={t('clubs.createSubtitle')}><form onSubmit={submit} className="grid gap-5"><Input name="name" label={t('clubs.name')} maxLength={100} required/><Select name="category" label={t('clubs.category')} placeholder={t('clubs.categoryPlaceholder')} defaultValue="" required options={categoryKeys.map(key=>({label:t(`clubs.categories.${key}`),value:t(`clubs.categories.${key}`)}))}/><Textarea name="description" label={t('clubs.description')} rows={6} maxLength={2000} required/><Input name="logo" type="file" accept="image/*" label={t('clubs.logo')}/><Input name="cover" type="file" accept="image/*" label={t('clubs.cover')}/><div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>nav(-1)}>{t('common.discard')}</Button><Button type="submit" loading={mutation.isPending}>{t('clubs.createClub')}</Button></div></form></Editor>}

export function EventCreatePage(){const{t}=useTranslation();const nav=useNavigate();const toast=useToast();const[params]=useSearchParams();const clubs=useClubs(true);const mutation=useCreateEvent();const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();mutation.mutate(new FormData(e.currentTarget),{onSuccess:r=>{toast.success(t('events.created'));nav(`/events/${r.id}`)},onError:()=>toast.error(t('events.createError'))})};return <Editor title={t('events.createEvent')} subtitle={t('events.createSubtitle')}><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Select name="clubId" label={t('events.organizerClub')} defaultValue={params.get('clubId')||''} placeholder={t('events.clubPlaceholder')} required options={(clubs.data||[]).filter(c=>c.currentUserRole==='CLUB_ADMIN').map(c=>({label:c.name,value:c.id}))}/></div><div className="sm:col-span-2"><Input name="title" label={t('events.eventTitle')} required/></div><Input name="startsAt" type="datetime-local" label={t('events.startTime')} required/><Input name="endsAt" type="datetime-local" label={t('events.endTime')}/><Input name="location" label={t('events.location')} required/><Select name="category" label={t('events.category')} defaultValue={t('clubs.categories.socialResponsibility')} options={categoryKeys.map(key=>({label:t(`clubs.categories.${key}`),value:t(`clubs.categories.${key}`)}))}/><div className="sm:col-span-2"><Input name="poster" type="file" accept="image/*" label={t('events.poster')}/></div><div className="sm:col-span-2"><Textarea name="description" label={t('events.description')} rows={6} required/></div><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="ghost" onClick={()=>nav(-1)}>{t('common.discard')}</Button><Button type="submit" loading={mutation.isPending}>{t('events.publish')}</Button></div></form></Editor>}
function Editor({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){const{t}=useTranslation();return <div className="mx-auto max-w-3xl"><p className="text-sm font-semibold text-primary">{t('editor.eyebrow')}</p><h1 className="font-heading text-3xl font-extrabold">{title}</h1><p className="mb-6 text-muted-foreground">{subtitle}</p><Card><CardContent>{children}</CardContent></Card></div>}
